services:
  app:
    build:
      context: docker
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USERNAME:-user}
        GROUPNAME: ${GROUPNAME:-group}
    working_dir: /app
    volumes:
      - .:/app
